// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parking.Domain;
using Parking.Infrastructure.Persistence.Tenant;

#nullable disable

namespace Parking.Infrastructure.Persistence.Tenant.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260403065228_AddLojistaAllowGrantBeforeEntry")]
    partial class AddLojistaAllowGrantBeforeEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "cash_session_status", new[] { "OPEN", "CLOSED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "payment_method", new[] { "PIX", "CARD", "CASH" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "payment_status", new[] { "PENDING", "PAID", "FAILED", "EXPIRED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "ticket_status", new[] { "OPEN", "AWAITING_PAYMENT", "CLOSED" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.AlertRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.CashSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("actual_amount");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("expected_amount");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<CashSessionStatus>("Status")
                        .HasColumnType("cash_session_status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_cash_sessions");

                    b.ToTable("cash_sessions", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.ClientRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("LojistaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lojista_id");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("plate");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("Plate")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_plate");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.ClientWalletRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BalanceHours")
                        .HasColumnType("integer")
                        .HasColumnName("balance_hours");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.HasKey("Id")
                        .HasName("pk_client_wallets");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_client_wallets_client_id");

                    b.ToTable("client_wallets", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.IdempotencyStoreRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Route")
                        .HasColumnType("text")
                        .HasColumnName("route");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.HasKey("Key", "Route")
                        .HasName("pk_idempotency_store");

                    b.ToTable("idempotency_store", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.LojistaGrantRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Hours")
                        .HasColumnType("integer")
                        .HasColumnName("hours");

                    b.Property<Guid>("LojistaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lojista_id");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("plate");

                    b.HasKey("Id")
                        .HasName("pk_lojista_grants");

                    b.HasIndex("LojistaId", "CreatedAt")
                        .HasDatabaseName("ix_lojista_grants_lojista_id_created_at");

                    b.ToTable("lojista_grants", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.LojistaRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowGrantBeforeEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_grant_before_entry");

                    b.Property<decimal>("HourPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hour_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_lojistas");

                    b.ToTable("lojistas", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.LojistaWalletRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BalanceHours")
                        .HasColumnType("integer")
                        .HasColumnName("balance_hours");

                    b.Property<Guid>("LojistaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lojista_id");

                    b.HasKey("Id")
                        .HasName("pk_lojista_wallets");

                    b.HasIndex("LojistaId")
                        .IsUnique()
                        .HasDatabaseName("ix_lojista_wallets_lojista_id");

                    b.ToTable("lojista_wallets", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.OperatorEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_operator_events");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_operator_events_user_id_created_at");

                    b.ToTable("operator_events", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.PackageOrderRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LojistaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lojista_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("Settlement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("settlement");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_package_orders");

                    b.ToTable("package_orders", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.PaymentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailedReason")
                        .HasColumnType("text")
                        .HasColumnName("failed_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<PaymentMethod?>("Method")
                        .HasColumnType("payment_method")
                        .HasColumnName("method");

                    b.Property<Guid?>("PackageOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_order_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<PaymentStatus>("Status")
                        .HasColumnType("payment_status")
                        .HasColumnName("status");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_idempotency_key");

                    b.HasIndex("PackageOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_package_order_id")
                        .HasFilter("package_order_id IS NOT NULL");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_ticket_id")
                        .HasFilter("ticket_id IS NOT NULL");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.PixTransactionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("ProviderStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_status");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qr_code");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_pix_transactions");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("ix_pix_transactions_payment_id")
                        .HasFilter("active = true");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_pix_transactions_transaction_id");

                    b.ToTable("pix_transactions", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.RechargePackageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("Hours")
                        .HasColumnType("integer")
                        .HasColumnName("hours");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_recharge_packages");

                    b.ToTable("recharge_packages", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.SchemaMigrationRow", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.HasKey("Version")
                        .HasName("pk_schema_migrations");

                    b.ToTable("schema_migrations", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.SettingsRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_hour");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.TicketRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EntryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_time");

                    b.Property<DateTimeOffset?>("ExitTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_time");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("plate");

                    b.Property<TicketStatus>("Status")
                        .HasColumnType("ticket_status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("Plate")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_plate")
                        .HasFilter("status IN ('OPEN', 'AWAITING_PAYMENT')");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.WalletLedgerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeltaHours")
                        .HasColumnType("integer")
                        .HasColumnName("delta_hours");

                    b.Property<Guid?>("LojistaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lojista_id");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("Settlement")
                        .HasColumnType("text")
                        .HasColumnName("settlement");

                    b.HasKey("Id")
                        .HasName("pk_wallet_ledger");

                    b.ToTable("wallet_ledger", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.WalletUsageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("HoursUsed")
                        .HasColumnType("integer")
                        .HasColumnName("hours_used");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_usages");

                    b.ToTable("wallet_usages", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Tenant.WebhookReceiptRow", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("TransactionId")
                        .HasName("pk_webhook_receipts");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_webhook_receipts_processed_at");

                    b.ToTable("webhook_receipts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
