package com.estacionamento.parking.ui

/** SPEC_FRONTEND §9 — literais usados no Android. */
object UiStrings {
    const val B1 = "Entrar"
    const val B2 = "Nova entrada"
    const val B3 = "Registrar problema"
    const val B4 = "Registrar saída (checkout)"
    const val B5 = "Pagar"
    const val B6 = "PIX"
    const val B7 = "Cartão"
    const val B8 = "Dinheiro"
    const val B9 = "Copiar código PIX"
    const val B10 = "Gerar novo QR"
    const val B11 = "Voltar ao início"
    const val B12 = "Caixa"
    const val B13 = "Configurações"
    const val B14 = "Abrir caixa"
    const val B15 = "Fechar caixa"
    const val B16 = "Comprar horas"
    const val B17 = "Histórico"
    const val B18 = "Selecionar"
    const val B20 = "Gestão"
    const val B21 = "Operação"
    const val D1 = "Confirmar recebimento em dinheiro neste valor?"
    const val D2 = "Confirmar compra a crédito interno? O valor será registrado."
    const val S1 = "Nenhum veículo no pátio."
    const val S2 = "Sem conexão. Algumas ações ficam bloqueadas."
    const val S3 = "Dados podem estar desatualizados (offline)."
    const val S4 = "Ticket encerrado."
    const val S5 = "Abra o caixa para habilitar dinheiro."
    const val S6 = "Pagamento online indisponível offline. Reconecte-se."
    const val S7 = "QR expirado."
    const val S8 = "Tempo limite de espera do pagamento. Use “Gerar novo QR”."
    const val S9 = "Acesso negado"
    const val S10 = "Você não pode abrir esta área com seu perfil."
    const val S11 = "Sessão de caixa"
    const val S12 = "Nenhum pacote cadastrado para este tipo."
    const val S15 = "Informe o ID do estacionamento (UUID) para continuar."
    const val T1 = "Problema registrado."
    const val T2 = "Entrada registrada."
    const val T3 = "Saída registrada. Nada a pagar."
    const val T4 = "Pagamento confirmado."
    const val T5 = "Código copiado."
    const val T6 = "Alerta: divergência no caixa acima do limite."
    const val T7 = "Configurações salvas."
    const val T8 = "Compra concluída."
    const val T9 = "Não foi possível sincronizar uma operação. Verifique na lista de tickets."
    /** SPEC §5.3 offline — fila §10 (texto operacional alinhado ao fluxo). */
    const val TQueueSync = "Sem rede: operação na fila e será enviada ao reconectar."
    const val E1 = "Operador bloqueado. Procure o gestor."
    const val E2 = "Aguarde antes de tentar de novo."
    const val E3 = "Preencha este campo."
    const val E4 = "Formato de placa inválido."
    const val E5 = "Já existe ticket em aberto para esta placa."
    const val E6 = "Não foi possível registrar a saída neste estado."
    const val E7 = "Pagamento falhou. Escolha outro método ou tente novamente."
    const val E8 = "Valor enviado não confere com o ticket."
    const val Sair = "Sair"
    const val Confirmar = "Confirmar"
    const val Voltar = "Voltar"
    const val Continuar = "Continuar"
    const val Placa = "Placa do veículo"
    const val Salvar = "Salvar"
    const val Credito = "Crédito"
    const val Pix = "PIX"
}
